package com.fredastone.pandacore.constants;

public enum RoleName {
	ROLE_CUSTOMER,ROLE_ENGINEER,ROLE_MARKETING,ROLE_FINANCE,ROLE_AGENT,ROLE_HR,ROLE_MANAGER,ROLE_SENIOR_MANAGER,ROLE_SUPPORT, ROLE_EMPLOYEE
}
