package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

import com.fredastone.pandacore.constants.AgentType;
import com.fredastone.pandacore.constants.IdType;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

/**
 * TAgentsMeta generated by hbm2java
 */
@Data
@Entity
@Table(name = "t_agent_meta",schema="panda_core")
@Setter @Getter
public class AgentMeta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6438370408233233490L;
	

	@Id
	@Column(name = "userid", unique = true, nullable = false, length = 36)
	private String userid;
	
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private User user;
	
	
	private String profilepath;
	private String contractdocpath;
	
	@Min(1)
	private int villageid;
	private String address;
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", insertable=false,updatable=false, nullable = false, length = 29)
	private Date createdon;
	
	@Min(0)
	@Max(100)
	private float agentcommissionrate;
	
	@Column(name="isdeactivated",insertable=false,updatable=true)
	private boolean isdeactivated;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "deactivatedon", length = 13)
	private Date deactivatedon;
	
	@Column(name="isactive",insertable=false,updatable=true)
	private boolean isactive;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "activatedon", length = 13)
	private Date activatedon;
	
	private float shoplong;
	private float shoplat;
	
	@NotEmpty
	private String companyname;
	
	@NotEmpty
	private String postaladdress;
	
	@NotEmpty
	private String tinnumber;
	private String coipath;
	
	@Enumerated(EnumType.STRING)
	private AgentType agenttype;
	
	
	@NotNull
	@Enumerated(EnumType.STRING)
	private IdType idtype;
	
	@NotEmpty
	private String idnumber;
}
