package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Data;

/**
 * TAgentsMeta generated by hbm2java
 */
@Data
@Entity
@Table(name = "t_agents_meta")
public class AgentsMeta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;


	@Id

	@Column(name = "id", unique = true, nullable = false)
	private int id;
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "agentid")
	private Agent TAgents;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "approvedbytwo")
	private Employees TEmployeesByApprovedbytwo;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "approvedbyone")
	private Employees TEmployeesByApprovedbyone;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "approvedbytworole")
	private TRole TRoleByApprovedbytworole;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "approvedbyonerole")
	private TRole TRoleByApprovedbyonerole;
	
	@Column(name = "profilepath")
	private String profilepath;
	
	@Column(name = "contractdocpath")
	private String contractdocpath;
	
	@Column(name = "villageid", nullable = false)
	private int villageid;
	
	@Column(name = "address")
	private String address;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createon", nullable = false, length = 29)
	private Date createon;


	

}
