package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * TApprovalTypes generated by hbm2java
 */
@Data
@Entity
@Table(name = "t_approval_types",schema="panda_core")
public class ApprovalTypes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id

	@Column(name = "id", unique = true, nullable = false)
	private short id;

	@Column(name = "name", nullable = false, length = 30)
	private String name;

	

}
