package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Data;

/**
 * TApprovals generated by hbm2java
 */
@Data
@Entity
@Table(name = "t_approvals",schema="panda_core")
public class Approval implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 36)
	private String id;
	
	@Column(name = "approvaltype", nullable = false)
	private int approvalType;
	
	@Column(name = "approver", nullable = false, length = 36)
	private String approver;
	
	@Column(name = "approvalorder", nullable = false)
	private int approvalorder;
	
	@Column(name = "approverrole", nullable = false)
	private String approverrole;
	
	@Column(name = "status", nullable = false)
	private short status;
	
	@Column(name = "externalreference", length = 36)
	private String externalreference;
	
	@Column(name = "description")
	private String description;
	
	@Basic(optional=false)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon",insertable=false,updatable=false, nullable = false, length = 29)
	private Date createdon;

}
