package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TApprovalTypes generated by hbm2java
 */
@Entity
@Table(name = "t_approval_types")
public class ApprovalTypes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id

	@Column(name = "id", unique = true, nullable = false)
	private short id;

	@Column(name = "name", nullable = false, length = 30)
	private String name;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TApprovalTypes")
	private Set<Approvals> TApprovalses = new HashSet<Approvals>(0);

}
