package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TCustomerMeta generated by hbm2java
 */
@Entity
@Table(name = "t_customer_meta")
public class CustomerMeta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 914203693448600046L;
	private CustomerMetaId id;
	private Villages TVillages;

	public CustomerMeta() {
	}

	public CustomerMeta(CustomerMetaId id) {
		this.id = id;
	}

	public CustomerMeta(CustomerMetaId id, Villages TVillages) {
		this.id = id;
		this.TVillages = TVillages;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "customerid", column = @Column(name = "customerid", nullable = false, length = 36)),
			@AttributeOverride(name = "secondaryphone", column = @Column(name = "secondaryphone", length = 36)),
			@AttributeOverride(name = "secondaryemail", column = @Column(name = "secondaryemail")),
			@AttributeOverride(name = "dateofbirth", column = @Column(name = "dateofbirth", length = 13)),
			@AttributeOverride(name = "idtype", column = @Column(name = "idtype")),
			@AttributeOverride(name = "idno", column = @Column(name = "idno", length = 50)),
			@AttributeOverride(name = "sex", column = @Column(name = "sex")),
			@AttributeOverride(name = "title", column = @Column(name = "title")),
			@AttributeOverride(name = "consentformpath", column = @Column(name = "consentformpath")),
			@AttributeOverride(name = "idcopypath", column = @Column(name = "idcopypath")),
			@AttributeOverride(name = "profilephotopath", column = @Column(name = "profilephotopath")),
			@AttributeOverride(name = "homecordinates", column = @Column(name = "homecordinates")),
			@AttributeOverride(name = "address", column = @Column(name = "address", length = 60)),
			@AttributeOverride(name = "villageid", column = @Column(name = "villageid")) })
	public CustomerMetaId getId() {
		return this.id;
	}

	public void setId(CustomerMetaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "villageid", insertable = false, updatable = false)
	public Villages getTVillages() {
		return this.TVillages;
	}

	public void setTVillages(Villages TVillages) {
		this.TVillages = TVillages;
	}

}
