package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotEmpty;

import com.fredastone.pandacore.constants.IdType;

import lombok.Data;

/**
 * TCustomerMeta generated by hbm2java
 */
@Data
@Entity
@Table(name = "t_customer_meta",schema="panda_core")
public class CustomerMeta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	private String userid;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private User user;
	
	private int villageid;
	
	private String secondaryphone;
	private String secondaryemail;
	
	@Enumerated(EnumType.STRING)
	private IdType idtype;
	
	@NotEmpty
	private String idnumber;
	
	private String consentformpath;
	
	private String idcopypath;
	private String profilephotopath;
	
	@NotEmpty
	private String address;
	
	private String housephotopath;
	
	
	private float homelat;
	private float homelong;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="createdon",insertable=false,updatable=false)
	private Date createdon;



}
