package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TCustomer generated by hbm2java
 */
@Entity
@Table(name = "t_customer")
public class Customer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String firstname;
	private String middlename;
	private String lastname;
	private Short isactive;
	private Serializable email;
	private String primaryphone;
	private Date createdon;
	private Set<Installation> TInstallations = new HashSet<Installation>(0);
	private Set<Lease> TLeases = new HashSet<Lease>(0);

	public Customer() {
	}

	public Customer(String id, String firstname, String middlename, String lastname, String primaryphone,
			Date createdon) {
		this.id = id;
		this.firstname = firstname;
		this.middlename = middlename;
		this.lastname = lastname;
		this.primaryphone = primaryphone;
		this.createdon = createdon;
	}

	public Customer(String id, String firstname, String middlename, String lastname, Short isactive,
			Serializable email, String primaryphone, Date createdon, Set<Installation> TInstallations,
			Set<Lease> TLeases) {
		this.id = id;
		this.firstname = firstname;
		this.middlename = middlename;
		this.lastname = lastname;
		this.isactive = isactive;
		this.email = email;
		this.primaryphone = primaryphone;
		this.createdon = createdon;
		this.TInstallations = TInstallations;
		this.TLeases = TLeases;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "firstname", nullable = false, length = 20)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "middlename", nullable = false, length = 20)
	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	@Column(name = "lastname", nullable = false, length = 20)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "isactive")
	public Short getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Short isactive) {
		this.isactive = isactive;
	}

	@Column(name = "email")
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	@Column(name = "primaryphone", nullable = false, length = 20)
	public String getPrimaryphone() {
		return this.primaryphone;
	}

	public void setPrimaryphone(String primaryphone) {
		this.primaryphone = primaryphone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", nullable = false, length = 29)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCustomer")
	public Set<Installation> getTInstallations() {
		return this.TInstallations;
	}

	public void setTInstallations(Set<Installation> TInstallations) {
		this.TInstallations = TInstallations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCustomer")
	public Set<Lease> getTLeases() {
		return this.TLeases;
	}

	public void setTLeases(Set<Lease> TLeases) {
		this.TLeases = TLeases;
	}

}
