package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TCustomerMetaId generated by hbm2java
 */
@Embeddable
public class CustomerMetaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String customerid;
	private String secondaryphone;
	private Serializable secondaryemail;
	private Date dateofbirth;
	private Short idtype;
	private String idno;
	private Short sex;
	private Short title;
	private String consentformpath;
	private String idcopypath;
	private String profilephotopath;
	private String homecordinates;
	private String address;
	private Integer villageid;

	public CustomerMetaId() {
	}

	public CustomerMetaId(String customerid) {
		this.customerid = customerid;
	}

	public CustomerMetaId(String customerid, String secondaryphone, Serializable secondaryemail, Date dateofbirth,
			Short idtype, String idno, Short sex, Short title, String consentformpath, String idcopypath,
			String profilephotopath, String homecordinates, String address, Integer villageid) {
		this.customerid = customerid;
		this.secondaryphone = secondaryphone;
		this.secondaryemail = secondaryemail;
		this.dateofbirth = dateofbirth;
		this.idtype = idtype;
		this.idno = idno;
		this.sex = sex;
		this.title = title;
		this.consentformpath = consentformpath;
		this.idcopypath = idcopypath;
		this.profilephotopath = profilephotopath;
		this.homecordinates = homecordinates;
		this.address = address;
		this.villageid = villageid;
	}

	@Column(name = "customerid", nullable = false, length = 36)
	public String getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}

	@Column(name = "secondaryphone", length = 36)
	public String getSecondaryphone() {
		return this.secondaryphone;
	}

	public void setSecondaryphone(String secondaryphone) {
		this.secondaryphone = secondaryphone;
	}

	@Column(name = "secondaryemail")
	public Serializable getSecondaryemail() {
		return this.secondaryemail;
	}

	public void setSecondaryemail(Serializable secondaryemail) {
		this.secondaryemail = secondaryemail;
	}

	@Column(name = "dateofbirth", length = 13)
	public Date getDateofbirth() {
		return this.dateofbirth;
	}

	public void setDateofbirth(Date dateofbirth) {
		this.dateofbirth = dateofbirth;
	}

	@Column(name = "idtype")
	public Short getIdtype() {
		return this.idtype;
	}

	public void setIdtype(Short idtype) {
		this.idtype = idtype;
	}

	@Column(name = "idno", length = 50)
	public String getIdno() {
		return this.idno;
	}

	public void setIdno(String idno) {
		this.idno = idno;
	}

	@Column(name = "sex")
	public Short getSex() {
		return this.sex;
	}

	public void setSex(Short sex) {
		this.sex = sex;
	}

	@Column(name = "title")
	public Short getTitle() {
		return this.title;
	}

	public void setTitle(Short title) {
		this.title = title;
	}

	@Column(name = "consentformpath")
	public String getConsentformpath() {
		return this.consentformpath;
	}

	public void setConsentformpath(String consentformpath) {
		this.consentformpath = consentformpath;
	}

	@Column(name = "idcopypath")
	public String getIdcopypath() {
		return this.idcopypath;
	}

	public void setIdcopypath(String idcopypath) {
		this.idcopypath = idcopypath;
	}

	@Column(name = "profilephotopath")
	public String getProfilephotopath() {
		return this.profilephotopath;
	}

	public void setProfilephotopath(String profilephotopath) {
		this.profilephotopath = profilephotopath;
	}

	@Column(name = "homecordinates")
	public String getHomecordinates() {
		return this.homecordinates;
	}

	public void setHomecordinates(String homecordinates) {
		this.homecordinates = homecordinates;
	}

	@Column(name = "address", length = 60)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "villageid")
	public Integer getVillageid() {
		return this.villageid;
	}

	public void setVillageid(Integer villageid) {
		this.villageid = villageid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CustomerMetaId))
			return false;
		CustomerMetaId castOther = (CustomerMetaId) other;

		return ((this.getCustomerid() == castOther.getCustomerid()) || (this.getCustomerid() != null
				&& castOther.getCustomerid() != null && this.getCustomerid().equals(castOther.getCustomerid())))
				&& ((this.getSecondaryphone() == castOther.getSecondaryphone())
						|| (this.getSecondaryphone() != null && castOther.getSecondaryphone() != null
								&& this.getSecondaryphone().equals(castOther.getSecondaryphone())))
				&& ((this.getSecondaryemail() == castOther.getSecondaryemail())
						|| (this.getSecondaryemail() != null && castOther.getSecondaryemail() != null
								&& this.getSecondaryemail().equals(castOther.getSecondaryemail())))
				&& ((this.getDateofbirth() == castOther.getDateofbirth())
						|| (this.getDateofbirth() != null && castOther.getDateofbirth() != null
								&& this.getDateofbirth().equals(castOther.getDateofbirth())))
				&& ((this.getIdtype() == castOther.getIdtype()) || (this.getIdtype() != null
						&& castOther.getIdtype() != null && this.getIdtype().equals(castOther.getIdtype())))
				&& ((this.getIdno() == castOther.getIdno()) || (this.getIdno() != null && castOther.getIdno() != null
						&& this.getIdno().equals(castOther.getIdno())))
				&& ((this.getSex() == castOther.getSex()) || (this.getSex() != null && castOther.getSex() != null
						&& this.getSex().equals(castOther.getSex())))
				&& ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null
						&& castOther.getTitle() != null && this.getTitle().equals(castOther.getTitle())))
				&& ((this.getConsentformpath() == castOther.getConsentformpath())
						|| (this.getConsentformpath() != null && castOther.getConsentformpath() != null
								&& this.getConsentformpath().equals(castOther.getConsentformpath())))
				&& ((this.getIdcopypath() == castOther.getIdcopypath()) || (this.getIdcopypath() != null
						&& castOther.getIdcopypath() != null && this.getIdcopypath().equals(castOther.getIdcopypath())))
				&& ((this.getProfilephotopath() == castOther.getProfilephotopath())
						|| (this.getProfilephotopath() != null && castOther.getProfilephotopath() != null
								&& this.getProfilephotopath().equals(castOther.getProfilephotopath())))
				&& ((this.getHomecordinates() == castOther.getHomecordinates())
						|| (this.getHomecordinates() != null && castOther.getHomecordinates() != null
								&& this.getHomecordinates().equals(castOther.getHomecordinates())))
				&& ((this.getAddress() == castOther.getAddress()) || (this.getAddress() != null
						&& castOther.getAddress() != null && this.getAddress().equals(castOther.getAddress())))
				&& ((this.getVillageid() == castOther.getVillageid()) || (this.getVillageid() != null
						&& castOther.getVillageid() != null && this.getVillageid().equals(castOther.getVillageid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCustomerid() == null ? 0 : this.getCustomerid().hashCode());
		result = 37 * result + (getSecondaryphone() == null ? 0 : this.getSecondaryphone().hashCode());
		result = 37 * result + (getSecondaryemail() == null ? 0 : this.getSecondaryemail().hashCode());
		result = 37 * result + (getDateofbirth() == null ? 0 : this.getDateofbirth().hashCode());
		result = 37 * result + (getIdtype() == null ? 0 : this.getIdtype().hashCode());
		result = 37 * result + (getIdno() == null ? 0 : this.getIdno().hashCode());
		result = 37 * result + (getSex() == null ? 0 : this.getSex().hashCode());
		result = 37 * result + (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result + (getConsentformpath() == null ? 0 : this.getConsentformpath().hashCode());
		result = 37 * result + (getIdcopypath() == null ? 0 : this.getIdcopypath().hashCode());
		result = 37 * result + (getProfilephotopath() == null ? 0 : this.getProfilephotopath().hashCode());
		result = 37 * result + (getHomecordinates() == null ? 0 : this.getHomecordinates().hashCode());
		result = 37 * result + (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37 * result + (getVillageid() == null ? 0 : this.getVillageid().hashCode());
		return result;
	}

}
