package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import lombok.Data;

/**
 * TEmployees generated by hbm2java
 */
@Data
@Entity
@Table(name = "t_employee",schema="panda_core")
public class EmployeeMeta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3433132068266148579L;
	private String userid;
	private User user;
	private boolean isterminated;
	private String mobile;
	private String profilepath;
	private Date createon;
	private Boolean isapproved;
	private Date terminatedon;
	private Date approvedon;
	private int village;
	private Set<Installation> installationsForCustomerid = new HashSet<Installation>(0);
	
	public EmployeeMeta() {
	}

	public EmployeeMeta(User user, boolean isterminated, Date createon, int village) {
		this.user = user;
		this.isterminated = isterminated;
		this.createon = createon;
		this.village = village;
	}

	public EmployeeMeta(User user, boolean isterminated, String mobile, String profilepath, Date createon,
			Boolean isapproved, Date terminatedon, Date approvedon, int village,Set<Installation> installationsForCustomerid) {
		this.user = user;
		this.isterminated = isterminated;
		this.mobile = mobile;
		this.profilepath = profilepath;
		this.createon = createon;
		this.isapproved = isapproved;
		this.terminatedon = terminatedon;
		this.approvedon = approvedon;
		this.village = village;
		this.installationsForCustomerid = installationsForCustomerid;
		
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "TUser"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "userid", unique = true, nullable = false, length = 36)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "isterminated", nullable = false)
	public boolean isIsterminated() {
		return this.isterminated;
	}

	public void setIsterminated(boolean isterminated) {
		this.isterminated = isterminated;
	}

	@Column(name = "mobile", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "profilepath")
	public String getProfilepath() {
		return this.profilepath;
	}

	public void setProfilepath(String profilepath) {
		this.profilepath = profilepath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createon", nullable = false, length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name = "isapproved")
	public Boolean getIsapproved() {
		return this.isapproved;
	}

	public void setIsapproved(Boolean isapproved) {
		this.isapproved = isapproved;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "terminatedon", length = 13)
	public Date getTerminatedon() {
		return this.terminatedon;
	}

	public void setTerminatedon(Date terminatedon) {
		this.terminatedon = terminatedon;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "approvedon", length = 13)
	public Date getApprovedon() {
		return this.approvedon;
	}

	public void setApprovedon(Date approvedon) {
		this.approvedon = approvedon;
	}

	@Column(name = "village", nullable = false)
	public int getVillage() {
		return this.village;
	}

	public void setVillage(int village) {
		this.village = village;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeMetaByCustomerid")
	public Set<Installation> getInstallationsForCustomerid() {
		return this.installationsForCustomerid;
	}

	public void setTInstallationsForCustomerid(Set<Installation> installationsForCustomerid) {
		this.installationsForCustomerid = installationsForCustomerid;
	}


}
