package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotEmpty;

import com.fredastone.pandacore.constants.IdType;

import lombok.Data;

/**
 * TEmployees generated by hbm2java
 */
@Data
@Entity
@Table(name = "t_employee_meta",schema="panda_core")
public class EmployeeMeta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3433132068266148579L;
	
	
	@Id
	private String userid;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private User user;
	
	@Column(name="isterminated",insertable=false,updatable=true)
	private boolean isterminated;
	
	@NotEmpty
	private String mobile;
	private String profilepath;
	private String tinnumber;
	
	@Column(name="createdon",insertable=false,updatable=false)
	private Date createdon;
	
	@Column(name="isapproved",insertable=false,updatable=true)
	private Boolean isapproved;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="terminatedon",insertable=false)
	private Date terminatedon;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="approvedon",insertable=false)
	private Date approvedon;
	
	@Min(1)
	private int village;
	
	@Enumerated(EnumType.STRING)
	private IdType idtype;
	
	@NotEmpty
	private String idnumber;


}
