package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TEmployees generated by hbm2java
 */
@Entity
@Table(name = "t_employees")
public class Employees implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String firstname;
	private String middlename;
	private String lastname;
	private Serializable personalemail;
	private Serializable companyemail;
	private boolean isterminated;
	private Serializable role;
	private String mobile;
	private String phone;
	private Date dateofbirth;
	private String profilepath;
	private Date createon;
	private Set<AgentsMeta> TAgentsMetasForApprovedbytwo = new HashSet<AgentsMeta>(0);
	private Set<Opex> TOpexes = new HashSet<Opex>(0);
	private Set<Installation> TInstallations = new HashSet<Installation>(0);
	private Set<AgentsMeta> TAgentsMetasForApprovedbyone = new HashSet<AgentsMeta>(0);
	private Set<Lease> TLeases = new HashSet<Lease>(0);
	private Set<Capex> TCapexes = new HashSet<Capex>(0);

	public Employees() {
	}

	public Employees(String id, String firstname, String lastname, Serializable personalemail,
			Serializable companyemail, boolean isterminated, Serializable role, Date createon) {
		this.id = id;
		this.firstname = firstname;
		this.lastname = lastname;
		this.personalemail = personalemail;
		this.companyemail = companyemail;
		this.isterminated = isterminated;
		this.role = role;
		this.createon = createon;
	}

	public Employees(String id, String firstname, String middlename, String lastname, Serializable personalemail,
			Serializable companyemail, boolean isterminated, Serializable role, String mobile, String phone,
			Date dateofbirth, String profilepath, Date createon, Set<AgentsMeta> TAgentsMetasForApprovedbytwo,
			Set<Opex> TOpexes, Set<Installation> TInstallations, Set<AgentsMeta> TAgentsMetasForApprovedbyone,
			Set<Lease> TLeases, Set<Capex> TCapexes) {
		this.id = id;
		this.firstname = firstname;
		this.middlename = middlename;
		this.lastname = lastname;
		this.personalemail = personalemail;
		this.companyemail = companyemail;
		this.isterminated = isterminated;
		this.role = role;
		this.mobile = mobile;
		this.phone = phone;
		this.dateofbirth = dateofbirth;
		this.profilepath = profilepath;
		this.createon = createon;
		this.TAgentsMetasForApprovedbytwo = TAgentsMetasForApprovedbytwo;
		this.TOpexes = TOpexes;
		this.TInstallations = TInstallations;
		this.TAgentsMetasForApprovedbyone = TAgentsMetasForApprovedbyone;
		this.TLeases = TLeases;
		this.TCapexes = TCapexes;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "firstname", nullable = false, length = 20)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "middlename", length = 20)
	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	@Column(name = "lastname", nullable = false, length = 20)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "personalemail", nullable = false)
	public Serializable getPersonalemail() {
		return this.personalemail;
	}

	public void setPersonalemail(Serializable personalemail) {
		this.personalemail = personalemail;
	}

	@Column(name = "companyemail", nullable = false)
	public Serializable getCompanyemail() {
		return this.companyemail;
	}

	public void setCompanyemail(Serializable companyemail) {
		this.companyemail = companyemail;
	}

	@Column(name = "isterminated", nullable = false)
	public boolean isIsterminated() {
		return this.isterminated;
	}

	public void setIsterminated(boolean isterminated) {
		this.isterminated = isterminated;
	}

	@Column(name = "role", nullable = false)
	public Serializable getRole() {
		return this.role;
	}

	public void setRole(Serializable role) {
		this.role = role;
	}

	@Column(name = "mobile", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateofbirth", length = 13)
	public Date getDateofbirth() {
		return this.dateofbirth;
	}

	public void setDateofbirth(Date dateofbirth) {
		this.dateofbirth = dateofbirth;
	}

	@Column(name = "profilepath")
	public String getProfilepath() {
		return this.profilepath;
	}

	public void setProfilepath(String profilepath) {
		this.profilepath = profilepath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createon", nullable = false, length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmployeesByApprovedbytwo")
	public Set<AgentsMeta> getTAgentsMetasForApprovedbytwo() {
		return this.TAgentsMetasForApprovedbytwo;
	}

	public void setTAgentsMetasForApprovedbytwo(Set<AgentsMeta> TAgentsMetasForApprovedbytwo) {
		this.TAgentsMetasForApprovedbytwo = TAgentsMetasForApprovedbytwo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmployees")
	public Set<Opex> getTOpexes() {
		return this.TOpexes;
	}

	public void setTOpexes(Set<Opex> TOpexes) {
		this.TOpexes = TOpexes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmployees")
	public Set<Installation> getTInstallations() {
		return this.TInstallations;
	}

	public void setTInstallations(Set<Installation> TInstallations) {
		this.TInstallations = TInstallations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmployeesByApprovedbyone")
	public Set<AgentsMeta> getTAgentsMetasForApprovedbyone() {
		return this.TAgentsMetasForApprovedbyone;
	}

	public void setTAgentsMetasForApprovedbyone(Set<AgentsMeta> TAgentsMetasForApprovedbyone) {
		this.TAgentsMetasForApprovedbyone = TAgentsMetasForApprovedbyone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmployees")
	public Set<Lease> getTLeases() {
		return this.TLeases;
	}

	public void setTLeases(Set<Lease> TLeases) {
		this.TLeases = TLeases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmployees")
	public Set<Capex> getTCapexes() {
		return this.TCapexes;
	}

	public void setTCapexes(Set<Capex> TCapexes) {
		this.TCapexes = TCapexes;
	}

}
