package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TEquipment generated by hbm2java
 */
@Entity
@Table(name = "t_equipment")
public class Equipment implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	private String id;
	private EquipCategory TEquipCategory;
	private String name;
	private String model;
	private Date dateofmanufacture;
	private boolean available;
	private String description;
	private String serial;
	private BigDecimal quantity;
	private Date createdon;

	public Equipment() {
	}

	public Equipment(String id, EquipCategory TEquipCategory, String name, String model, boolean available,
			String description, String serial, BigDecimal quantity, Date createdon) {
		this.id = id;
		this.TEquipCategory = TEquipCategory;
		this.name = name;
		this.model = model;
		this.available = available;
		this.description = description;
		this.serial = serial;
		this.quantity = quantity;
		this.createdon = createdon;
	}

	public Equipment(String id, EquipCategory TEquipCategory, String name, String model, Date dateofmanufacture,
			boolean available, String description, String serial, BigDecimal quantity, Date createdon) {
		this.id = id;
		this.TEquipCategory = TEquipCategory;
		this.name = name;
		this.model = model;
		this.dateofmanufacture = dateofmanufacture;
		this.available = available;
		this.description = description;
		this.serial = serial;
		this.quantity = quantity;
		this.createdon = createdon;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoryid", nullable = false)
	public EquipCategory getTEquipCategory() {
		return this.TEquipCategory;
	}

	public void setTEquipCategory(EquipCategory TEquipCategory) {
		this.TEquipCategory = TEquipCategory;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "model", nullable = false)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateofmanufacture", length = 29)
	public Date getDateofmanufacture() {
		return this.dateofmanufacture;
	}

	public void setDateofmanufacture(Date dateofmanufacture) {
		this.dateofmanufacture = dateofmanufacture;
	}

	@Column(name = "available", nullable = false)
	public boolean isAvailable() {
		return this.available;
	}

	public void setAvailable(boolean available) {
		this.available = available;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "serial", nullable = false)
	public String getSerial() {
		return this.serial;
	}

	public void setSerial(String serial) {
		this.serial = serial;
	}

	@Column(name = "quantity", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", nullable = false, length = 29)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

}
