package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TEquipCategory generated by hbm2java
 */
@Entity
@Table(name = "t_equip_category")
public class EquipCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private short id;
	private String name;
	private String description;
	private Date createon;
	private Boolean isactive;
	private Set<Equipment> TEquipments = new HashSet<Equipment>(0);

	public EquipCategory() {
	}

	public EquipCategory(short id, String name, Date createon) {
		this.id = id;
		this.name = name;
		this.createon = createon;
	}

	public EquipCategory(short id, String name, String description, Date createon, Boolean isactive,
			Set<Equipment> TEquipments) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.createon = createon;
		this.isactive = isactive;
		this.TEquipments = TEquipments;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createon", nullable = false, length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name = "isactive")
	public Boolean getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEquipCategory")
	public Set<Equipment> getTEquipments() {
		return this.TEquipments;
	}

	public void setTEquipments(Set<Equipment> TEquipments) {
		this.TEquipments = TEquipments;
	}

}
