package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Data;

/**
 * TInstallation generated by hbm2java
 */

@Data
@Entity
@Table(name = "t_installation",schema="panda_core")
public class Installation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7014692064098319088L;
	private String id;
	private String customerid;
	private String employeeid;
	private float homelong;
	private float homelat;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "starttime", nullable = false, length = 29)
	private Date starttime;
	private Date endtime;
	
	private Date createdon;
	private String deviceserial;
	

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon",insertable=false, nullable = false, length = 29)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endtime", nullable = false, length = 29)
	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}
}
