package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TInstallation generated by hbm2java
 */
@Entity
@Table(name = "t_installation")
public class Installation implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	private String id;
	private Customer TCustomer;
	private Employees TEmployees;
	private Serializable coordinates;
	private Date createdon;
	private Date endtime;

	public Installation() {
	}

	public Installation(String id, Customer TCustomer, Employees TEmployees, Serializable coordinates,
			Date createdon, Date endtime) {
		this.id = id;
		this.TCustomer = TCustomer;
		this.TEmployees = TEmployees;
		this.coordinates = coordinates;
		this.createdon = createdon;
		this.endtime = endtime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customerid", nullable = false)
	public Customer getTCustomer() {
		return this.TCustomer;
	}

	public void setTCustomer(Customer TCustomer) {
		this.TCustomer = TCustomer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "saleagentid", nullable = false)
	public Employees getTEmployees() {
		return this.TEmployees;
	}

	public void setTEmployees(Employees TEmployees) {
		this.TEmployees = TEmployees;
	}

	@Column(name = "coordinates", nullable = false)
	public Serializable getCoordinates() {
		return this.coordinates;
	}

	public void setCoordinates(Serializable coordinates) {
		this.coordinates = coordinates;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", nullable = false, length = 29)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endtime", nullable = false, length = 29)
	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

}
