package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Data;

/**
 * TLease generated by hbm2java
 */
@Data
@Entity
@Table(name = "t_lease",schema="panda_core")
public class Lease implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -6594190583348198883L;
	
	@Id
	@Column(name = "id", unique = true, nullable = false, length = 36)
	private String id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "leaseofferid", nullable = false)
	private LeaseOffer leaseOffer;
	
	@Column(name = "customerid", nullable = false, length = 36)
	private String customerid;
	
	@Column(name = "initialdeposit", nullable = false)
	private float initialdeposit;
	
	@Column(name = "couponcode", nullable = false)
	private String couponcode;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateinstalled", nullable = false, length = 29)
	private Date dateinstalled;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", nullable = false, insertable=false,updatable=false,length = 29)
	private Date createdon;
	
	@Column(name = "saleagentid", nullable = false)
	private String saleagentid;
	
	@Column(name = "dailypayment", nullable = false)
	private float dailypayment;
	
	@Column(name = "totalleaseperiod", nullable = false)
	private int totalleaseperiod;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expectedfinishdate", nullable = false, length = 29)
	private Date expectedfinishdate;
	
	@Column(name = "totalleasevalue", nullable = false)
	private float totalleasevalue;
	
	@Column(name = "iscompleted", nullable = false)
	private boolean iscompleted;

	@Column(name = "isactivated", nullable = false)
	private boolean isactivated;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "paymentcompletedon", nullable = false, length = 29)
	private Date paymentcompletedon;
}
