package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Getter;
import lombok.Setter;

/**
 * TLeaseOffer generated by hbm2java
 */

@Entity
@Table(name = "t_lease_offer",schema="panda_core")
public class LeaseOffer implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -8387305479040781270L;
	private int id;
	private Product product;
	private String code;
	private short leaseperiod;
	
	@Getter @Setter
	@Column(name = "percentlease", nullable = false)
	private short percentlease;
	private float recurrentpaymentamount;
	private boolean isactive;
	private float intialdeposit;
	private String name;
	private String description;
	private Date createdon;	

	
	@Id
	@SequenceGenerator(name="panda_core.s_lease_offer",sequenceName="panda_core.s_lease_offer",allocationSize=1)
	@GeneratedValue(generator="panda_core.s_lease_offer")
	@Column(name = "id",unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productid", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "leaseperiod", nullable = false)
	public short getLeaseperiod() {
		return this.leaseperiod;
	}

	public void setLeaseperiod(short leaseperiod) {
		this.leaseperiod = leaseperiod;
	}


	@Column(name = "recurrentpaymentamount", nullable = false, precision = 131089, scale = 0)
	public float getRecurrentpaymentamount() {
		return this.recurrentpaymentamount;
	}

	public void setRecurrentpaymentamount(float recurrentpaymentamount) {
		this.recurrentpaymentamount = recurrentpaymentamount;
	}

	@Column(name = "isactive", nullable = false)
	public boolean isIsactive() {
		return this.isactive;
	}

	public void setIsactive(boolean isactive) {
		this.isactive = isactive;
	}

	@Column(name = "intialdeposit", nullable = false, precision = 131089, scale = 0)
	public float getIntialdeposit() {
		return this.intialdeposit;
	}

	public void setIntialdeposit(float intialdeposit) {
		this.intialdeposit = intialdeposit;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", length = 29)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	
}
