package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TLeasePayments generated by hbm2java
 */
@Entity
@Table(name = "t_lease_payments")
public class LeasePayments implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String id;
	private String productid;
	private String customerid;
	private BigDecimal amount;
	private String payeename;
	private String payeemobilenumber;
	private short paymentchannel;
	private short paymentstatus;
	private String transactionid;
	private String channeltransactionid;
	private String channelstatuscode;
	private String channelmessage;
	private Date createdon;

	public LeasePayments() {
	}

	public LeasePayments(String id, String productid, String customerid, BigDecimal amount, short paymentchannel,
			short paymentstatus, String transactionid, Date createdon) {
		this.id = id;
		this.productid = productid;
		this.customerid = customerid;
		this.amount = amount;
		this.paymentchannel = paymentchannel;
		this.paymentstatus = paymentstatus;
		this.transactionid = transactionid;
		this.createdon = createdon;
	}

	public LeasePayments(String id, String productid, String customerid, BigDecimal amount, String payeename,
			String payeemobilenumber, short paymentchannel, short paymentstatus, String transactionid,
			String channeltransactionid, String channelstatuscode, String channelmessage, Date createdon) {
		this.id = id;
		this.productid = productid;
		this.customerid = customerid;
		this.amount = amount;
		this.payeename = payeename;
		this.payeemobilenumber = payeemobilenumber;
		this.paymentchannel = paymentchannel;
		this.paymentstatus = paymentstatus;
		this.transactionid = transactionid;
		this.channeltransactionid = channeltransactionid;
		this.channelstatuscode = channelstatuscode;
		this.channelmessage = channelmessage;
		this.createdon = createdon;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "productid", nullable = false, length = 36)
	public String getProductid() {
		return this.productid;
	}

	public void setProductid(String productid) {
		this.productid = productid;
	}

	@Column(name = "customerid", nullable = false, length = 36)
	public String getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}

	@Column(name = "amount", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "payeename", length = 100)
	public String getPayeename() {
		return this.payeename;
	}

	public void setPayeename(String payeename) {
		this.payeename = payeename;
	}

	@Column(name = "payeemobilenumber", length = 20)
	public String getPayeemobilenumber() {
		return this.payeemobilenumber;
	}

	public void setPayeemobilenumber(String payeemobilenumber) {
		this.payeemobilenumber = payeemobilenumber;
	}

	@Column(name = "paymentchannel", nullable = false)
	public short getPaymentchannel() {
		return this.paymentchannel;
	}

	public void setPaymentchannel(short paymentchannel) {
		this.paymentchannel = paymentchannel;
	}

	@Column(name = "paymentstatus", nullable = false)
	public short getPaymentstatus() {
		return this.paymentstatus;
	}

	public void setPaymentstatus(short paymentstatus) {
		this.paymentstatus = paymentstatus;
	}

	@Column(name = "transactionid", nullable = false, length = 20)
	public String getTransactionid() {
		return this.transactionid;
	}

	public void setTransactionid(String transactionid) {
		this.transactionid = transactionid;
	}

	@Column(name = "channeltransactionid", length = 36)
	public String getChanneltransactionid() {
		return this.channeltransactionid;
	}

	public void setChanneltransactionid(String channeltransactionid) {
		this.channeltransactionid = channeltransactionid;
	}

	@Column(name = "channelstatuscode", length = 5)
	public String getChannelstatuscode() {
		return this.channelstatuscode;
	}

	public void setChannelstatuscode(String channelstatuscode) {
		this.channelstatuscode = channelstatuscode;
	}

	@Column(name = "channelmessage")
	public String getChannelmessage() {
		return this.channelmessage;
	}

	public void setChannelmessage(String channelmessage) {
		this.channelmessage = channelmessage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", nullable = false, length = 29)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

}
