package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TOpexType generated by hbm2java
 */
@Entity
@Table(name = "t_opex_type")
public class OpexType implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	private short id;
	private String name;
	private Set<Opex> TOpexes = new HashSet<Opex>(0);

	public OpexType() {
	}

	public OpexType(short id) {
		this.id = id;
	}

	public OpexType(short id, String name, Set<Opex> TOpexes) {
		this.id = id;
		this.name = name;
		this.TOpexes = TOpexes;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TOpexType")
	public Set<Opex> getTOpexes() {
		return this.TOpexes;
	}

	public void setTOpexes(Set<Opex> TOpexes) {
		this.TOpexes = TOpexes;
	}

}
