package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.Data;

/**
 * TOpexType generated by hbm2java
 */
@Data
@Entity
@Table(name = "t_opex_type",schema="opera_core")
public class OpexType implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	@Id

	@Column(name = "id", unique = true, nullable = false)
	private short id;
	
	@Column(name = "name", length = 50)
	private String name;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TOpexType")
	private Set<Opex> TOpexes = new HashSet<Opex>(0);



}
