package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TParishes generated by hbm2java
 */
@Entity
@Table(name = "t_parishes")
public class Parishes implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	private int id;
	private Subcounty TSubcounty;
	private String name;
	private Set<Villages> TVillageses = new HashSet<Villages>(0);

	public Parishes() {
	}

	public Parishes(int id, Subcounty TSubcounty) {
		this.id = id;
		this.TSubcounty = TSubcounty;
	}

	public Parishes(int id, Subcounty TSubcounty, String name, Set<Villages> TVillageses) {
		this.id = id;
		this.TSubcounty = TSubcounty;
		this.name = name;
		this.TVillageses = TVillageses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subcountyid", nullable = false)
	public Subcounty getTSubcounty() {
		return this.TSubcounty;
	}

	public void setTSubcounty(Subcounty TSubcounty) {
		this.TSubcounty = TSubcounty;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TParishes")
	public Set<Villages> getTVillageses() {
		return this.TVillageses;
	}

	public void setTVillageses(Set<Villages> TVillageses) {
		this.TVillageses = TVillageses;
	}

}
