package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPaymentChannel generated by hbm2java
 */
@Entity
@Table(name = "t_payment_channel")
public class PaymentChannel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private short id;
	private String channelname;
	private String channelcode;
	private Boolean isenabled;
	private String description;
	private Date createdon;

	public PaymentChannel() {
	}

	public PaymentChannel(short id, String channelname, String channelcode, String description, Date createdon) {
		this.id = id;
		this.channelname = channelname;
		this.channelcode = channelcode;
		this.description = description;
		this.createdon = createdon;
	}

	public PaymentChannel(short id, String channelname, String channelcode, Boolean isenabled, String description,
			Date createdon) {
		this.id = id;
		this.channelname = channelname;
		this.channelcode = channelcode;
		this.isenabled = isenabled;
		this.description = description;
		this.createdon = createdon;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	@Column(name = "channelname", nullable = false, length = 20)
	public String getChannelname() {
		return this.channelname;
	}

	public void setChannelname(String channelname) {
		this.channelname = channelname;
	}

	@Column(name = "channelcode", nullable = false, length = 5)
	public String getChannelcode() {
		return this.channelcode;
	}

	public void setChannelcode(String channelcode) {
		this.channelcode = channelcode;
	}

	@Column(name = "isenabled")
	public Boolean getIsenabled() {
		return this.isenabled;
	}

	public void setIsenabled(Boolean isenabled) {
		this.isenabled = isenabled;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", nullable = false, length = 29)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

}
