package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

/**
 * TProducts generated by hbm2java
 */
@Data
@EqualsAndHashCode(callSuper=false)
@Entity
@Setter
@Getter
@Table(name = "t_product",schema="panda_core")
public class Product extends BaseArrayEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "id", unique = true, nullable = false, length = 36)
	private String id;
	
	@Column(name = "name", nullable = false)
	private String name;
	
	@Column(name = "serial", nullable = false)
	private String serialNumber;
	
    @Type(type="string-array")
	@Column(name = "equipmentlist",columnDefinition="varchar[]" ,nullable = false)
	private String[] equipmentlist;
	
	@Column(name = "unitcostselling", nullable = false, precision = 131089, scale = 0)
	private float unitcostselling;
	
	@Column(name = "description", nullable = false)
	private String description;
		
	@Column(name = "thumbnail", nullable = false)
	private String thumbnail;

	@Column(name="isactive",nullable=false)
	private Boolean isActive;
	
	@Column(name="isleasable",nullable=true)
	private Boolean isleasable;
	
	@Column(name="usestoken",nullable=false)
	private Boolean usestoken;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", nullable = false,insertable = false,updatable=false, length = 29)
	private Date createdon;
	
}
