package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TProducts generated by hbm2java
 */
@Entity
@Table(name = "t_products")
public class Products implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	private String id;
	private String name;
	private Serializable equipmentlist;
	private BigDecimal unitcostselling;
	private String description;
	private String thumbnail;
	private Date createdon;
	private Set<Lease> TLeases = new HashSet<Lease>(0);
	private Set<LeaseOffer> TLeaseOffers = new HashSet<LeaseOffer>(0);

	public Products() {
	}

	public Products(String id, String name, Serializable equipmentlist, BigDecimal unitcostselling, String description,
			String thumbnail, Date createdon) {
		this.id = id;
		this.name = name;
		this.equipmentlist = equipmentlist;
		this.unitcostselling = unitcostselling;
		this.description = description;
		this.thumbnail = thumbnail;
		this.createdon = createdon;
	}

	public Products(String id, String name, Serializable equipmentlist, BigDecimal unitcostselling, String description,
			String thumbnail, Date createdon, Set<Lease> TLeases, Set<LeaseOffer> TLeaseOffers) {
		this.id = id;
		this.name = name;
		this.equipmentlist = equipmentlist;
		this.unitcostselling = unitcostselling;
		this.description = description;
		this.thumbnail = thumbnail;
		this.createdon = createdon;
		this.TLeases = TLeases;
		this.TLeaseOffers = TLeaseOffers;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "equipmentlist", nullable = false)
	public Serializable getEquipmentlist() {
		return this.equipmentlist;
	}

	public void setEquipmentlist(Serializable equipmentlist) {
		this.equipmentlist = equipmentlist;
	}

	@Column(name = "unitcostselling", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getUnitcostselling() {
		return this.unitcostselling;
	}

	public void setUnitcostselling(BigDecimal unitcostselling) {
		this.unitcostselling = unitcostselling;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "thumbnail", nullable = false)
	public String getThumbnail() {
		return this.thumbnail;
	}

	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", nullable = false, length = 29)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TProducts")
	public Set<Lease> getTLeases() {
		return this.TLeases;
	}

	public void setTLeases(Set<Lease> TLeases) {
		this.TLeases = TLeases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TProducts")
	public Set<LeaseOffer> getTLeaseOffers() {
		return this.TLeaseOffers;
	}

	public void setTLeaseOffers(Set<LeaseOffer> TLeaseOffers) {
		this.TLeaseOffers = TLeaseOffers;
	}

}
