package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.fredastone.pandacore.constants.RoleName;

import lombok.Data;

/**
 * TRole generated by hbm2java
 */
@Data
@Entity
@Table(name = "t_role",schema="panda_core")
public class Role implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "id", unique = true, nullable = false)
	private short id;
	
	@Column(name = "name", length = 50)
    @NotNull
    @Enumerated(EnumType.STRING)
    private RoleName name;
	

	@Column(name = "description")
	private String description;
	
	public Role(){
		
	}
	
	public Role(short id) {
		this.id = id;
	}
	
	public Role(RoleName rolename) {
		this.name = rolename;
	}

}
