package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TSales generated by hbm2java
 */
@Entity
@Table(name = "t_sales")
public class Sales implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String id;
	private Agent TAgents;
	private String itemtype;
	private String saletype;
	private BigDecimal amount;
	private String description;
	private String scannedserial;
	private BigDecimal agentcommission;
	private BigDecimal long_;
	private BigDecimal lat;
	private short salestatus;
	private Date createdon;
	private Set<SaleRollback> TSaleRollbacks = new HashSet<SaleRollback>(0);

	public Sales() {
	}

	public Sales(String id, Agent TAgents, BigDecimal amount, String description, BigDecimal agentcommission,
			BigDecimal long_, BigDecimal lat, short salestatus, Date createdon) {
		this.id = id;
		this.TAgents = TAgents;
		this.amount = amount;
		this.description = description;
		this.agentcommission = agentcommission;
		this.long_ = long_;
		this.lat = lat;
		this.salestatus = salestatus;
		this.createdon = createdon;
	}

	public Sales(String id, Agent TAgents, String itemtype, String saletype, BigDecimal amount, String description,
			String scannedserial, BigDecimal agentcommission, BigDecimal long_, BigDecimal lat, short salestatus,
			Date createdon, Set<SaleRollback> TSaleRollbacks) {
		this.id = id;
		this.TAgents = TAgents;
		this.itemtype = itemtype;
		this.saletype = saletype;
		this.amount = amount;
		this.description = description;
		this.scannedserial = scannedserial;
		this.agentcommission = agentcommission;
		this.long_ = long_;
		this.lat = lat;
		this.salestatus = salestatus;
		this.createdon = createdon;
		this.TSaleRollbacks = TSaleRollbacks;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "agentid", nullable = false)
	public Agent getTAgents() {
		return this.TAgents;
	}

	public void setTAgents(Agent TAgents) {
		this.TAgents = TAgents;
	}

	@Column(name = "itemtype")
	public String getItemtype() {
		return this.itemtype;
	}

	public void setItemtype(String itemtype) {
		this.itemtype = itemtype;
	}

	@Column(name = "saletype")
	public String getSaletype() {
		return this.saletype;
	}

	public void setSaletype(String saletype) {
		this.saletype = saletype;
	}

	@Column(name = "amount", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "scannedserial", length = 50)
	public String getScannedserial() {
		return this.scannedserial;
	}

	public void setScannedserial(String scannedserial) {
		this.scannedserial = scannedserial;
	}

	@Column(name = "agentcommission", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getAgentcommission() {
		return this.agentcommission;
	}

	public void setAgentcommission(BigDecimal agentcommission) {
		this.agentcommission = agentcommission;
	}

	@Column(name = "long_", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getLong_() {
		return this.long_;
	}

	public void setLong_(BigDecimal long_) {
		this.long_ = long_;
	}

	@Column(name = "lat_", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getLat() {
		return this.lat;
	}

	public void setLat(BigDecimal lat) {
		this.lat = lat;
	}

	@Column(name = "salestatus", nullable = false)
	public short getSalestatus() {
		return this.salestatus;
	}

	public void setSalestatus(short salestatus) {
		this.salestatus = salestatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", nullable = false, length = 29)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSales")
	public Set<SaleRollback> getTSaleRollbacks() {
		return this.TSaleRollbacks;
	}

	public void setTSaleRollbacks(Set<SaleRollback> TSaleRollbacks) {
		this.TSaleRollbacks = TSaleRollbacks;
	}

}
