package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TSubcounty generated by hbm2java
 */
@Entity
@Table(name = "t_subcounty")
public class Subcounty implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	private int id;
	private County TCounty;
	private String name;
	private Set<Parishes> TParisheses = new HashSet<Parishes>(0);

	public Subcounty() {
	}

	public Subcounty(int id, County TCounty) {
		this.id = id;
		this.TCounty = TCounty;
	}

	public Subcounty(int id, County TCounty, String name, Set<Parishes> TParisheses) {
		this.id = id;
		this.TCounty = TCounty;
		this.name = name;
		this.TParisheses = TParisheses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "countyid", nullable = false)
	public County getTCounty() {
		return this.TCounty;
	}

	public void setTCounty(County TCounty) {
		this.TCounty = TCounty;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSubcounty")
	public Set<Parishes> getTParisheses() {
		return this.TParisheses;
	}

	public void setTParisheses(Set<Parishes> TParisheses) {
		this.TParisheses = TParisheses;
	}

}
