package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import lombok.Data;

/**
 * TSubcounty generated by hbm2java
 */
@Data
@Entity
@Table(name = "t_subcounty",schema="panda_core")
public class Subcounty implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	@Id
	@SequenceGenerator(name="panda_core.s_subcounty",sequenceName="panda_core.s_subcounty",allocationSize=1)
	@GeneratedValue(generator="panda_core.s_subcounty")
	@Column(name = "id", unique = true, nullable = false,updatable=false)
	private int id;
	
	@Column(name = "countyid", nullable = false)
	private int countyid;
	
	@Column(name = "name", length = 50)
	private String name;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subcountyid")
	private Set<Parish> parishes = new HashSet<Parish>(0);

	
}
