package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TTokensId generated by hbm2java
 */
@Embeddable
public class TokensId implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	private String leasepaymentid;
	private String token;
	private Date createdon;

	public TokensId() {
	}

	public TokensId(String leasepaymentid, Date createdon) {
		this.leasepaymentid = leasepaymentid;
		this.createdon = createdon;
	}

	public TokensId(String leasepaymentid, String token, Date createdon) {
		this.leasepaymentid = leasepaymentid;
		this.token = token;
		this.createdon = createdon;
	}

	@Column(name = "leasepaymentid", nullable = false, length = 36)
	public String getLeasepaymentid() {
		return this.leasepaymentid;
	}

	public void setLeasepaymentid(String leasepaymentid) {
		this.leasepaymentid = leasepaymentid;
	}

	@Column(name = "token", length = 256)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "createdon", nullable = false, length = 29)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TokensId))
			return false;
		TokensId castOther = (TokensId) other;

		return ((this.getLeasepaymentid() == castOther.getLeasepaymentid())
				|| (this.getLeasepaymentid() != null && castOther.getLeasepaymentid() != null
						&& this.getLeasepaymentid().equals(castOther.getLeasepaymentid())))
				&& ((this.getToken() == castOther.getToken()) || (this.getToken() != null
						&& castOther.getToken() != null && this.getToken().equals(castOther.getToken())))
				&& ((this.getCreatedon() == castOther.getCreatedon()) || (this.getCreatedon() != null
						&& castOther.getCreatedon() != null && this.getCreatedon().equals(castOther.getCreatedon())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLeasepaymentid() == null ? 0 : this.getLeasepaymentid().hashCode());
		result = 37 * result + (getToken() == null ? 0 : this.getToken().hashCode());
		result = 37 * result + (getCreatedon() == null ? 0 : this.getCreatedon().hashCode());
		return result;
	}

}
