package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TTokens generated by hbm2java
 */
@Entity
@Table(name = "t_tokens")
public class Tokens implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private TokensId id;

	public Tokens() {
	}

	public Tokens(TokensId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "leasepaymentid", column = @Column(name = "leasepaymentid", nullable = false, length = 36)),
			@AttributeOverride(name = "token", column = @Column(name = "token", length = 256)),
			@AttributeOverride(name = "createdon", column = @Column(name = "createdon", nullable = false, length = 29)) })
	public TokensId getId() {
		return this.id;
	}

	public void setId(TokensId id) {
		this.id = id;
	}

}
