package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import com.fredastone.pandacore.constants.TokenTypes;

import lombok.Data;

/**
 * TTokens generated by hbm2java
 */

@Data
@Entity
@Table(name = "t_token",schema="panda_core")
public class Token implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	private String leasepaymentid;
	private String token;
	private int times;
	private int days;
	
	@Column(name = "type")
    @NotNull
    @Enumerated(EnumType.ORDINAL)
    private TokenTypes type;

	
	@Temporal(TemporalType.DATE)
	@Column(updatable=false,insertable=false,nullable=false)
	private Date createdon;

}
