package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TTotalLeasePayments generated by hbm2java
 */
@Entity
@Table(name = "t_total_lease_payments")
public class TotalLeasePayments implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	private TotalLeasePaymentsId id;

	public TotalLeasePayments() {
	}

	public TotalLeasePayments(TotalLeasePaymentsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false, length = 36)),
			@AttributeOverride(name = "paymenttransactionid", column = @Column(name = "paymenttransactionid", length = 36)),
			@AttributeOverride(name = "customerid", column = @Column(name = "customerid", nullable = false, length = 36)),
			@AttributeOverride(name = "productid", column = @Column(name = "productid", nullable = false, length = 36)),
			@AttributeOverride(name = "amountpaid", column = @Column(name = "amountpaid", nullable = false, precision = 131089, scale = 0)),
			@AttributeOverride(name = "totalpaid", column = @Column(name = "totalpaid", nullable = false, precision = 131089, scale = 0)),
			@AttributeOverride(name = "totalexpected", column = @Column(name = "totalexpected", nullable = false, precision = 131089, scale = 0)),
			@AttributeOverride(name = "totalissuedtokens", column = @Column(name = "totalissuedtokens", nullable = false)),
			@AttributeOverride(name = "createdon", column = @Column(name = "createdon", nullable = false, length = 29)),
			@AttributeOverride(name = "nextpaymentdate", column = @Column(name = "nextpaymentdate", nullable = false, length = 29)) })
	public TotalLeasePaymentsId getId() {
		return this.id;
	}

	public void setId(TotalLeasePaymentsId id) {
		this.id = id;
	}

}
