package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TTotalLeasePaymentsId generated by hbm2java
 */
@Embeddable
public class TotalLeasePaymentsId implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	private String id;
	private String paymenttransactionid;
	private String customerid;
	private String productid;
	private BigDecimal amountpaid;
	private BigDecimal totalpaid;
	private BigDecimal totalexpected;
	private int totalissuedtokens;
	private Date createdon;
	private Date nextpaymentdate;

	public TotalLeasePaymentsId() {
	}

	public TotalLeasePaymentsId(String id, String customerid, String productid, BigDecimal amountpaid,
			BigDecimal totalpaid, BigDecimal totalexpected, int totalissuedtokens, Date createdon,
			Date nextpaymentdate) {
		this.id = id;
		this.customerid = customerid;
		this.productid = productid;
		this.amountpaid = amountpaid;
		this.totalpaid = totalpaid;
		this.totalexpected = totalexpected;
		this.totalissuedtokens = totalissuedtokens;
		this.createdon = createdon;
		this.nextpaymentdate = nextpaymentdate;
	}

	public TotalLeasePaymentsId(String id, String paymenttransactionid, String customerid, String productid,
			BigDecimal amountpaid, BigDecimal totalpaid, BigDecimal totalexpected, int totalissuedtokens,
			Date createdon, Date nextpaymentdate) {
		this.id = id;
		this.paymenttransactionid = paymenttransactionid;
		this.customerid = customerid;
		this.productid = productid;
		this.amountpaid = amountpaid;
		this.totalpaid = totalpaid;
		this.totalexpected = totalexpected;
		this.totalissuedtokens = totalissuedtokens;
		this.createdon = createdon;
		this.nextpaymentdate = nextpaymentdate;
	}

	@Column(name = "id", nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "paymenttransactionid", length = 36)
	public String getPaymenttransactionid() {
		return this.paymenttransactionid;
	}

	public void setPaymenttransactionid(String paymenttransactionid) {
		this.paymenttransactionid = paymenttransactionid;
	}

	@Column(name = "customerid", nullable = false, length = 36)
	public String getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}

	@Column(name = "productid", nullable = false, length = 36)
	public String getProductid() {
		return this.productid;
	}

	public void setProductid(String productid) {
		this.productid = productid;
	}

	@Column(name = "amountpaid", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getAmountpaid() {
		return this.amountpaid;
	}

	public void setAmountpaid(BigDecimal amountpaid) {
		this.amountpaid = amountpaid;
	}

	@Column(name = "totalpaid", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getTotalpaid() {
		return this.totalpaid;
	}

	public void setTotalpaid(BigDecimal totalpaid) {
		this.totalpaid = totalpaid;
	}

	@Column(name = "totalexpected", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getTotalexpected() {
		return this.totalexpected;
	}

	public void setTotalexpected(BigDecimal totalexpected) {
		this.totalexpected = totalexpected;
	}

	@Column(name = "totalissuedtokens", nullable = false)
	public int getTotalissuedtokens() {
		return this.totalissuedtokens;
	}

	public void setTotalissuedtokens(int totalissuedtokens) {
		this.totalissuedtokens = totalissuedtokens;
	}

	@Column(name = "createdon", nullable = false, length = 29)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "nextpaymentdate", nullable = false, length = 29)
	public Date getNextpaymentdate() {
		return this.nextpaymentdate;
	}

	public void setNextpaymentdate(Date nextpaymentdate) {
		this.nextpaymentdate = nextpaymentdate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TotalLeasePaymentsId))
			return false;
		TotalLeasePaymentsId castOther = (TotalLeasePaymentsId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getPaymenttransactionid() == castOther.getPaymenttransactionid())
						|| (this.getPaymenttransactionid() != null && castOther.getPaymenttransactionid() != null
								&& this.getPaymenttransactionid().equals(castOther.getPaymenttransactionid())))
				&& ((this.getCustomerid() == castOther.getCustomerid()) || (this.getCustomerid() != null
						&& castOther.getCustomerid() != null && this.getCustomerid().equals(castOther.getCustomerid())))
				&& ((this.getProductid() == castOther.getProductid()) || (this.getProductid() != null
						&& castOther.getProductid() != null && this.getProductid().equals(castOther.getProductid())))
				&& ((this.getAmountpaid() == castOther.getAmountpaid()) || (this.getAmountpaid() != null
						&& castOther.getAmountpaid() != null && this.getAmountpaid().equals(castOther.getAmountpaid())))
				&& ((this.getTotalpaid() == castOther.getTotalpaid()) || (this.getTotalpaid() != null
						&& castOther.getTotalpaid() != null && this.getTotalpaid().equals(castOther.getTotalpaid())))
				&& ((this.getTotalexpected() == castOther.getTotalexpected())
						|| (this.getTotalexpected() != null && castOther.getTotalexpected() != null
								&& this.getTotalexpected().equals(castOther.getTotalexpected())))
				&& (this.getTotalissuedtokens() == castOther.getTotalissuedtokens())
				&& ((this.getCreatedon() == castOther.getCreatedon()) || (this.getCreatedon() != null
						&& castOther.getCreatedon() != null && this.getCreatedon().equals(castOther.getCreatedon())))
				&& ((this.getNextpaymentdate() == castOther.getNextpaymentdate())
						|| (this.getNextpaymentdate() != null && castOther.getNextpaymentdate() != null
								&& this.getNextpaymentdate().equals(castOther.getNextpaymentdate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getPaymenttransactionid() == null ? 0 : this.getPaymenttransactionid().hashCode());
		result = 37 * result + (getCustomerid() == null ? 0 : this.getCustomerid().hashCode());
		result = 37 * result + (getProductid() == null ? 0 : this.getProductid().hashCode());
		result = 37 * result + (getAmountpaid() == null ? 0 : this.getAmountpaid().hashCode());
		result = 37 * result + (getTotalpaid() == null ? 0 : this.getTotalpaid().hashCode());
		result = 37 * result + (getTotalexpected() == null ? 0 : this.getTotalexpected().hashCode());
		result = 37 * result + this.getTotalissuedtokens();
		result = 37 * result + (getCreatedon() == null ? 0 : this.getCreatedon().hashCode());
		result = 37 * result + (getNextpaymentdate() == null ? 0 : this.getNextpaymentdate().hashCode());
		return result;
	}

}
