package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Data;

/**
 * TTotalLeasePaymentsId generated by hbm2java
 */
@Data
@Entity
@Table(name="t_total_lease_payments",schema="panda_core")
public class TotalLeasePayments implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	@Id
	private String id;
	private String leaseid;
	private float lastpaidamount;
	private float totalamountpaid;
	private float totalamountowed;
	private float residueamount;
	private int times;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="createdon",updatable=false,insertable=false,nullable=false)
	private Date createdon;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="nextpaymentdate",updatable=true,insertable=true,nullable=false)
	private Date nextpaymentdate;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="updatedon",insertable=true,nullable=false)
	private Date updatedon;

}
