package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import lombok.Data;

/**
 * TRole generated by hbm2java
 */
@Data
@Entity
@Table(name = "t_role")
public class TRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "id", unique = true, nullable = false)
	private short id;
	
	@Column(name = "name", length = 50)
    @NotNull
    @Enumerated(EnumType.STRING)
    private RoleName name;
	

	@Column(name = "description")
	private String description;
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRole")
	private List<TUserRole> tUserRoles = new ArrayList<TUserRole>(0);
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRoleByApprovedbytworole")
	private List<AgentsMeta> tAgentsMetasForApprovedbytworole = new ArrayList<AgentsMeta>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRoleByApprovedbyonerole")
	private List<AgentsMeta> tAgentsMetasForApprovedbyonerole = new ArrayList<AgentsMeta>(0);



}
