package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

import lombok.Data;

/**
 * TUsers generated by hbm2java
 */

@Data
@Entity
@Table(name = "t_user",schema="panda_core")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id

	@Column(name = "id", unique = true, nullable = false, length = 36)
	@JsonProperty(access = Access.READ_ONLY)
	private String id;
	
	@NotEmpty
	@Column(name = "username", nullable = false, length = 30)
	private String username;
	
	
	private String password;
	
	@Column(name = "isactive",insertable=false,updatable=true, nullable = false)
	private boolean isactive;
	
	@Column(name = "isapproved",insertable=false,updatable=true, nullable = false)
	private boolean isapproved;
	
	@JsonIgnore
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "passwordreseton",insertable=false,updatable=true, length = 29)
	private Date passwordreseton;
	
	@Basic(optional=false)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon",insertable=false,updatable=false, nullable = false, length = 29)
	private Date createdon;
	
	@NotEmpty(message="Usertype cannot be empty")
	@Size(max=30)
	@Column(name = "usertype", nullable = false, length = 30)
	private String usertype;
	
	@NotEmpty
	@Size(max=20)
	@Column(name = "firstname", nullable = false, length = 20)
	private String firstname;
	
	@Size(max=20,message="Middlename cannot be more than 20 in length")
	@Column(name = "middlename", length = 20)
	private String middlename;
	
	@NotNull
	@Size(max=20)
	@Column(name = "lastname", nullable = false, length = 20)
	private String lastname;
	

	@Size(max=50)
	@NotEmpty
	@Column(name = "email", nullable = false, length = 50)
	private String email;


	@Column(name = "primaryphone", nullable = false, length = 20)
	private String primaryphone;
	

	@Column(name = "companyemail", nullable = false, length = 20)
	private String companyemail;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "dateofbirth", length = 13)
	private Date dateofbirth;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "lastlogon", length = 13)
	@JsonIgnore
	private Date lastlogon;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "updatedon",insertable=false,updatable=false,nullable=true, length = 13)
	private Date updatedon;
	
		
	
	@JsonIgnore
	@NotEmpty
	@Size(max=60)
	@Column(name = "password", nullable = false, length = 60)
	public String getPassword() {
		return this.password;
	}
	
	@JsonProperty
	public void setPassword(String password)
	{
		this.password = password;
	}
	
	
}
