package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

import lombok.Data;

/**
 * TUsers generated by hbm2java
 */

@Data
@Entity
@Table(name = "t_user",schema="panda_core")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id

	@Column(name = "id", unique = true, nullable = false, length = 36)
	@JsonProperty(access = Access.READ_ONLY)
	private String id;
	
	@Column(name = "username", nullable = false, length = 30)
	private String username;
	
	@Column(name = "password", nullable = false, length = 30)
	private String password;
	
	@Column(name = "isactive", nullable = false)
	private boolean isactive;
	
	@JsonIgnore
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "passwordreseton", length = 29)
	private Date passwordreseton;
	
	@Basic(optional=false)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon",insertable=false,updatable=false, nullable = false, length = 29)
	private Date createdon;
	
	@Column(name = "usertype", nullable = false, length = 30)
	private String usertype;
	

	@Column(name = "firstname", nullable = false, length = 20)
	private String firstname;
	

	@Column(name = "middlename", length = 20)
	private String middlename;
	

	@Column(name = "lastname", nullable = false, length = 20)
	private String lastname;
	

	@Column(name = "email", nullable = false, length = 20)
	private String email;


	@Column(name = "primaryphone", nullable = false, length = 20)
	private String primaryphone;
	

	@Column(name = "companyemail", nullable = false, length = 20)
	private String companyemail;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "dateofbirth", length = 13)
	private Date dateofbirth;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "lastlogon", length = 13)
	@JsonIgnore
	private Date lastlogon;
	
	
//
//	@OneToOne(fetch = FetchType.LAZY, mappedBy = "user")
//	@JsonIgnore
//	private AgentMeta agentMeta;
//	
//	
//	@OneToOne(fetch = FetchType.LAZY, mappedBy = "user")
//	private EmployeeMeta employeeMeta;
//	
//
//	@OneToOne(fetch = FetchType.LAZY, mappedBy = "user")
//	private CustomerMeta customerMeta;



	
}
