package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TVillages generated by hbm2java
 */
@Entity
@Table(name = "t_villages")
public class Villages implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	private int id;
	private Parishes TParishes;
	private String name;
	private Set<CustomerMeta> TCustomerMetas = new HashSet<CustomerMeta>(0);

	public Villages() {
	}

	public Villages(int id, Parishes TParishes) {
		this.id = id;
		this.TParishes = TParishes;
	}

	public Villages(int id, Parishes TParishes, String name, Set<CustomerMeta> TCustomerMetas) {
		this.id = id;
		this.TParishes = TParishes;
		this.name = name;
		this.TCustomerMetas = TCustomerMetas;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parishid", nullable = false)
	public Parishes getTParishes() {
		return this.TParishes;
	}

	public void setTParishes(Parishes TParishes) {
		this.TParishes = TParishes;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TVillages")
	public Set<CustomerMeta> getTCustomerMetas() {
		return this.TCustomerMetas;
	}

	public void setTCustomerMetas(Set<CustomerMeta> TCustomerMetas) {
		this.TCustomerMetas = TCustomerMetas;
	}

}
