package com.fredastone.pandacore.entity;
// Generated Feb 7, 2019 1:36:16 AM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import lombok.Data;

/**
 * TVillages generated by hbm2java
 */
@Data
@Entity
@Table(name = "t_village",schema="panda_core")
public class Village implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	
	@Id
	@SequenceGenerator(name="panda_core.s_villages",sequenceName="panda_core.s_villages", allocationSize=1)
	@GeneratedValue(generator="panda_core.s_villages")
	@Column(name = "id", unique = true, nullable = false,updatable=false)
	private int id;
	
	@Column(name = "parishid", nullable = false)
	private int parishid;
	
	@Column(name = "name", length = 50)
	private String name;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getParishid() {
		return parishid;
	}

	public void setParishid(int parishid) {
		this.parishid = parishid;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
}
